[build]
  # This should match the "outputPath" in your angular.json
  publish = "dist/karukolpo-frontend/browser"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.karukolpocrafts.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20" # Match your local Node version
  NPM_FLAGS = "--legacy-peer-deps"